src/Entity/Cible.php
<?php

namespace App\Entity;

use App\Repository\CibleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ORM\Entity(repositoryClass=CibleRepository::class)
 */
class Cible
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Nom obligatoire")
     * @Assert\Length(
     *     min=3,
     *     max=20,
     *     minMessage="Merci de saisir plus de 3 caractères",
     *     maxMessage="Merci de saisir moins de 20 caractères"
     * )
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Prénom obligatoire")
     * @Assert\Length(
     *     min=3,
     *     max=20,
     *     minMessage="Merci de saisir plus de 3 caractères",
     *     maxMessage="Merci de saisir moins de 20 caractères"
     * )
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_code;

    /**
     * @ORM\ManyToOne(targetEntity=Nationalite::class, inversedBy="cibles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Mission::class)
     * @ORM\JoinTable(name="mission_cible",
     *      joinColumns={@ORM\JoinColumn(name="cible_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="mission_id", referencedColumnName="id")}
     * )
     */
    private $missions;

    public function __construct()
    {
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getNomCode(): ?string
    {
        return $this->nom_code;
    }

    public function setNomCode(string $nom_code): self
    {
        $this->nom_code = $nom_code;

        return $this;
    }

    public function getNationalite(): Nationalite|null
    {
        return $this->nationalite;
    }

    public function setNationalite(?Nationalite $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Mission $mission): self
    {
        if (!$this->missions->contains($mission)) {
            $this->missions->add($mission);
            $mission->addCible($this);
        }

        return $this;
    }

    public function removeMission(Mission $mission): self
    {
        if ($this->missions->removeElement($mission)) {
            $mission->removeCible($this);
        }

        return $this;
    }

    public function setMissions(Collection $missions): self
    {
        $this->missions = $missions;

        return $this;
    }


}

src/Form/CibleType.php
<?php

namespace App\Form;

use App\Entity\Cible;
use App\Entity\Nationalite;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CibleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'required' => true])
            ->add('prenom', TextType::class, [
                'required' => true])
            ->add('date_naissance', DateType::class, [
                'required' => true])
            ->add('nom_code', TextType::class, [
                'required' => true])
            ->add('nationalite', EntityType::class, [
                'class' => Nationalite::class,
                'choice_label' => 'nationalite',
                'required' => true
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cible::class,
        ]);
    }
}

src/Controller/CibleController.php
<?php

namespace App\Controller;

use App\Entity\Cible;
use App\Form\CibleType;
use App\Repository\CibleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/admin/cible')]
class CibleController extends AbstractController
{
    #[Route('/', name: 'cible_index', methods: ['GET'])]
    public function index(CibleRepository $cibleRepository): Response
    {
        return $this->render('cible/index.html.twig', [
            'cibles' => $cibleRepository->findAll(),
        ]);
    }

    #[Route('/admin/cible/new', name: 'cible_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $cible = new Cible();
        $form = $this->createForm(CibleType::class, $cible);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($cible);
            $entityManager->flush();

            return $this->redirectToRoute('cible_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cible/new.html.twig', [
            'cible' => $cible,
            'form' => $form,
        ]);
    }

    #[Route('/admin/cible/{id}', name: 'cible_show', methods: ['GET'])]
    public function show(Cible $cible): Response
    {
        return $this->render('cible/show.html.twig', [
            'cible' => $cible,
        ]);
    }

    #[Route('/admin/cible/{id}/edit', name: 'cible_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Cible $cible): Response
    {
        $form = $this->createForm(CibleType::class, $cible);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('cible_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('cible/edit.html.twig', [
            'cible' => $cible,
            'form' => $form,
        ]);
    }

    #[Route('/admin/cible/{id}', name: 'cible_delete', methods: ['POST'])]
    public function delete(Request $request, Cible $cible): Response
    {
        if ($this->isCsrfTokenValid('delete'.$cible->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($cible);
            $entityManager->flush();
        }

        return $this->redirectToRoute('cible_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/cible/_delete_form.html.twig
<form method="post" action="{{ path('cible_delete', {'id': cible.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cible.id) }}">
    <button class="btn btn-primary">Supprimer</button>
</form>

templates/cible/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Sauvegarder') }}</button>
{{ form_end(form) }}

templates/cible/edit.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}Créer une cible{% endblock %}

{% block main %}
    <h1>Créer une cible</h1>

    {{ include('cible/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('cible_index') }}" class="btn btn-primary">Retour à la liste</a>

    {{ include('cible/_delete_form.html.twig') }}
{% endblock %}

templates/cible/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cible index{% endblock %}

{% block main %}
    <h1>Cible index</h1>

    <table class="table table-dark table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Date_naissance</th>
                <th>Nom_code</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for cible in cibles %}
            <tr>
                <td>{{ cible.id }}</td>
                <td>{{ cible.nom }}</td>
                <td>{{ cible.prenom }}</td>
                <td>{{ cible.dateNaissance ? cible.dateNaissance|date('Y-m-d') : '' }}</td>
                <td>{{ cible.nomCode }}</td>
                <td>
                    <a href="{{ path('cible_show', {'id': cible.id}) }}" class="btn btn-primary">Détails</a>
                    <a href="{{ path('cible_edit', {'id': cible.id}) }}" class="btn btn-primary">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('cible_new') }}" class="btn btn-primary">Créer une nouvelle cible</a>
    <a href="{{ path('admin_missions_list') }}" class="btn btn-primary">Retour à la liste des missions</a>
{% endblock %}

templates/cible/new.html.twig
{% extends 'admin/base.html.twig' %}

{% block title %}Nouvelle cible{% endblock %}

{% block main %}
    <h1>Créer une nouvelle cible</h1>

    {{ include('cible/_form.html.twig') }}

    <a href="{{ path('cible_index') }}" class="btn btn-primary">Retour à la liste</a>
{% endblock %}

templates/cible/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cible{% endblock %}

{% block main %}
    <h1>Cible</h1>

    <table class="table table-dark table-striped">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cible.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ cible.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ cible.prenom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ cible.dateNaissance ? cible.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nom_code</th>
                <td>{{ cible.nomCode }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('cible_index') }}" class="btn btn-primary">Retour à la liste</a>

    <a href="{{ path('cible_edit', {'id': cible.id}) }}" class="btn btn-primary">Modifier</a>

    {{ include('cible/_delete_form.html.twig') }}
{% endblock %}