src/Entity/Agent.php
<?php

namespace App\Entity;

use App\Repository\AgentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=AgentRepository::class)
 */
class Agent
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @ParamConverter("post", options={"id" = "post_id"})
     *
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Attention, le nom est obligatoire!")
     * @Assert\Length(
     *     min=3,
     *     max=20,
     *     minMessage= "Merci de remplir plus de 3 caractères.",
     *     maxMessage ="Merci de ne pas remplir plus de 20 caractères."
     * )
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Le prénom est obligatoire")
     * @Assert\Length(
     *     min=3,
     *     max=20,
     *     minMessage="Merci de remplir plus de 3 caractères.",
     *     maxMessage="Merci de ne pas remplir plus de 20 caractères."
     * )
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string")
     *
     */
    private $nom_code;

    /**
     * @ORM\ManyToOne(targetEntity=Nationalite::class, inversedBy="agents")
     * @ORM\JoinColumn(nullable=false)
     */
    private $nationalite;

    /**
     * @ORM\ManyToMany(targetEntity=Specialite::class)
     * @ORM\JoinTable(name="agent_specialite",
     *      joinColumns={@ORM\JoinColumn(name="agent_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="specialite_id", referencedColumnName="id")}
     * )
     */
    private $specialites;

    /**
     * @ORM\ManyToMany(targetEntity=Mission::class)
     * @ORM\JoinTable(name="mission_agent",
     *      joinColumns={@ORM\JoinColumn(name="agent_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="mission_id", referencedColumnName="id")}
     * )
     */
    private $missions;

    public function __construct()
    {
        $this->specialites = new ArrayCollection();
        $this->missions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }


    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getNomCode(): ?string
    {
        return $this->nom_code;
    }

    public function setNomCode(string $nom_code): self
    {
        $this->nom_code = $nom_code;

        return $this;
    }

    public function getNationalite(): Nationalite
    {
        return $this->nationalite;
    }

    public function setNationalite(?Nationalite $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getSpecialites(): Collection
    {
        return $this->specialites;
    }

    public function addSpecialites(Specialite $specialite): self
    {
        if (!$this->specialites->contains($specialite)) {
            $this->specialites->add($specialite);
            $specialite->addAgent($this);
        }

        return $this;
    }

    public function removeSpecialites(Specialite $specialite): self
    {
        if($this->specialites->removeElement($specialite)) {
            $specialite->removeAgent($this);
        }

        return $this;
    }

    public function setSpecialites(Collection $specialites): self
    {
        $this->specialites = $specialites;

        return $this;
    }

    public function getMissions(): Collection
    {
        return $this->missions;
    }

    public function addMission(Mission $mission): self
    {
        if (!$this->missions->contains($mission)) {
            $this->missions->add($mission);
            $mission->addAgent($this);
        }

        return $this;
    }

    public function removeMission(Mission $mission): self
    {
        if ($this->missions->removeElement($mission)) {
            $mission->removeAgent($this);
        }

        return $this;
    }

    public function setMissions(Collection $missions): self
    {
        $this->missions = $missions;

        return $this;
    }
}

src/Entity/Mission.php
<?php

namespace App\Entity;

use App\Repository\MissionRepository;
use App\Validator\AgentSpecialiteMission;
use App\Validator\MissionCibleAgentNationality;
use App\Validator\MissionCibleAgentNationalityValidator;
use App\Validator\MissionContactMissionNationality;
use App\Validator\MissionContactMissionNationalityValidator;
use App\Validator\MissionPlanqueMissionNationality;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Mapping\ClassMetadata;

/**
 * @ORM\Entity(repositoryClass=MissionRepository::class)
 */
class Mission
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Attention, le titre doit être rempli!")
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Attention, la description doit être remplie!")
     * @Assert\Length(
     *     min=10,
     *     max=255,
     *     minMessage= "Merci de remplir plus de 10 caractères.",
     *     maxMessage ="Merci de ne pas remplir plus de 255 caractères."
     * )
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull(message="Attention, le nm de code doit être rempli!")
     * @Assert\Length(
     *     min=3,
     *     max=20,
     *     minMessage= "Merci de remplir plus de 3 caractères.",
     *     maxMessage ="Merci de ne pas remplir plus de 20 caractères."
     * )
     */
    private $nom_code;

    /**
     * @ORM\Column(type="date")
     */
    private $date_debut;

    /**
     * @ORM\Column(type="date")
     */
    private $date_fin;


    /**
     * @ORM\ManyToMany(targetEntity=Agent::class)
     * @ORM\JoinTable(name="mission_agent",
     *      joinColumns={@ORM\JoinColumn(name="mission_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="agent_id", referencedColumnName="id")}
     * )
     */
    private $agents;

    /**
     * @ORM\ManyToOne(targetEntity=Specialite::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $specialite;

    /**
     * @ORM\ManyToOne(targetEntity=Nationalite::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $nationalite;

    /**
     * @ORM\ManyToOne(targetEntity=StatutMission::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $statut;

    /**
     * @ORM\ManyToOne(targetEntity=TypeMission::class, inversedBy="missions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $type;

    /**
     * @ORM\ManyToMany(targetEntity=Planque::class)
     * @ORM\JoinTable(name="mission_planque",
     *      joinColumns={@ORM\JoinColumn(name="mission_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="planque_id", referencedColumnName="id")}
     * )
     */
    private $planques;

    /**
     * @ORM\ManyToMany(targetEntity=Contact::class)
     * @ORM\JoinTable(name="mission_contact",
     *      joinColumns={@ORM\JoinColumn(name="mission_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="contact_id", referencedColumnName="id")}
     * )
     */
    private $contacts;

    /**
     * @ORM\ManyToMany(targetEntity=Cible::class)
     * @ORM\JoinTable(name="mission_cible",
     *      joinColumns={@ORM\JoinColumn(name="mission_id", referencedColumnName="id")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="cible_id", referencedColumnName="id")}
     * )
     */
    private $cibles;

    public function __construct()
    {
        $this->agents= new ArrayCollection();
        $this->cibles = new ArrayCollection();
        $this->contacts= new ArrayCollection();
        $this->planques= new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNomCode(): ?string
    {
        return $this->nom_code;
    }

    public function setNomCode(string $nom_code): self
    {
        $this->nom_code = $nom_code;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getAgents(): Collection|null
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents->add($agent);
            $agent->addMission($this);
        }

        return $this;
    }


    public function removeAgent(Agent $agent): self
    {
        if ($this->agents->removeElement($agent)) {
            $agent->removeMission($this);
        }

        return $this;
    }

    public function setAgents(Collection $agents): self
    {
        $this->agents = $agents;

        return $this;
    }

    public function getSpecialite(): Specialite|null
    {
        return $this->specialite;
    }

    public function setSpecialite(?Specialite $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }

    public function getStatut(): StatutMission|null
    {
        return $this->statut;
    }

    public function setStatut(?StatutMission $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getType(): TypeMission|null
    {
        return $this->type;
    }

    public function setType(?TypeMission $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getTypeMission(): TypeMission
    {
        return $this->TypeMission;
    }

    public function setTypeMission(?TypeMission $TypeMission): self
    {
        $this->TypeMission = $TypeMission;

        return $this;
    }

    public function getPlanques(): Collection|null
    {
        return $this->planques;
    }

    public function addPlanque(Planque $planque): self
    {
        if (!$this->planques->contains($planque)) {
            $this->planques->add($planque);
            $planque->addMission($this);
        }

        return $this;
    }

    public function removePlanque(Planque $planque): self
    {
        if ($this->planques->removeElement($planque)) {
            $planque->removeMission($this);
        }

        return $this;
    }

    public function setPlanques(Collection $planques): self
    {
        $this->planques = $planques;

        return $this;
    }

    public function getContacts(): Collection|null
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts->add($contact);
            $contact->addMission($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            $contact->removeMission($this);
        }

        return $this;
    }

    public function setContacts(Collection $contacts): self
    {
        $this->contacts = $contacts;

        return $this;
    }

    public function getCibles(): Collection|null
    {
        return $this->cibles;
    }

    public function addCible(Cible $cible): self
    {
        if (!$this->cibles->contains($cible)) {
            $this->cibles->add($cible);
            $cible->addMission($this);
        }

        return $this;
    }

    public function removeCible(Cible $cible): self
    {
        if ($this->cibles->removeElement($cible)) {
            $cible->removeMission($this);
        }

        return $this;
    }

    public function setCibles(Collection $cibles): self
    {
        $this->cibles = $cibles;

        return $this;
    }

    public function getNationalite(): Nationalite|null
    {
        return $this->nationalite;
    }

    public function setNationalite(?Nationalite $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }


    public static function loadValidatorMetadata(ClassMetadata $metadata)
    {
        $metadata->addPropertyConstraint('agents', new MissionCibleAgentNationality());
        $metadata->addPropertyConstraint('contacts', new MissionContactMissionNationality());
        $metadata->addPropertyConstraint('planques', new MissionPlanqueMissionNationality());
        $metadata->addPropertyConstraint('agents', new AgentSpecialiteMission());
    }


}

templates/accueil.html.twig
{% extends 'base.html.twig' %}

 {% block main %}

     <div class="table table-dark table-striped">
         <table>
             <thead>
             <tr>
                 <td>Missions</td>
                 <td>Titre</td>
                 <td class="table-description">Description</td>
                 <td>Nom de code</td>
                 <td>Date de début</td>
                 <td>Date de fin</td>
                 <td>Agent</td>
                 <td>nationalite</td>
                 <td>contact</td>
                 <td>cible</td>
                 <td>typesMission</td>
                 <td>statut</td>
                 <td>planque</td>
                 <td>specialite</td>

             </tr>
             </thead>

             <tbody>
             {% for mission in missions %}
                 <tr>
                     <td>{{ mission.id }}</td>
                     <td>{{ mission.titre }}</td>
                     <td>{{ mission.description }}</td>
                     <td>{{ mission.nomCode }}</td>
                     <td>{{ mission.dateDebut|date("m/d/Y") }}</td>
                     <td>{{ mission.dateFin|date("m/d/Y") }}</td>
                     <td>
                         {% for agent in mission.getAgents().toArray() %}
                            {{ agent.nom }}
                         {%  endfor %}
                     </td>
                     <td>nationalite : {{ mission.nationalite.pays }}</td>
                     <td>
                         {% for contact in mission.contacts %}
                             {{ contact.nom }}
                         {%  endfor %}
                     </td>
                     <td>
                         {% for cible in mission.cibles %}
                             {{ cible.nom }}
                         {%  endfor %}
                     </td>
                     <td>
                         {% for typeMission in mission.type %}
                             {{ typeMission.nom }}
                         {%  endfor %}
                     </td>
                     <td>statut : {{ mission.statut.nom }}</td>
                     <td>
                         {% for planque in mission.planques %}
                             {{ planque.nomCode }}
                         {%  endfor %}
                      </td>
                     <td>specialite : {{ mission.specialite.nom }}</td>

                 </tr>
             {% endfor %}
             </tbody>
         </table>

     </div>
 {% endblock main %}

templates/base.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Secret Agence</title>
    {%  block stylesheets %}
        <link rel="stylesheet" href="{{ asset('assets/css/style.css') }}">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>"
    {% endblock stylesheets %}
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href={{ path('home') }}">
            <img class="header-top-image" src="{{ asset('assets/image/logo3.png') }}" alt="logo">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{{ path('admin_missions_list') }}">Liste des missions</a>
                    <a class="nav-link" href="{{ path('app_login') }}">Administrateur</a>
                    <a class="nav-link" href="{{ path('app_logout') }}">Se déconnecter</a>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <form class="d-flex"
                  action="{{ path('mission_search') }}">
                <label for="q">Rechercher des missions</label>
                <input class="form-control me-2" type="search" name="q" placeholder="Chercher une mission" aria-label="Search">
                <button class="btn btn-outline-success"
                        type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>
<main>
    {% block main %}

    {% endblock main %}
</main>
<footer>

</footer>
<script src="{{ asset('assets/js/global.js') }}"></script>
</body>

</html>